import networks_eliai

list_available_loras = networks_eliai.list_available_networks

available_loras = networks_eliai.available_networks
available_lora_aliases = networks_eliai.available_network_aliases
available_lora_hash_lookup = networks_eliai.available_network_hash_lookup
forbidden_lora_aliases = networks_eliai.forbidden_network_aliases
loaded_loras = networks_eliai.loaded_networks
